# Jekyll Resume Theme

# Site settings
title: my homepage
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: 
url: http://zch3ng.github.io
name: Zhang Cheng
job: student
home: applied chemistry
location: Department of Chemistry, Northeastern University, Shenyang
languages: chemistry
Down resume_username:
codepen_username:
twitter_username:
email_address: a541235117@163.com

# Build settings
markdown: kramdown

